version: '3'
services:
  traefik:
    image: traefik:v2.1
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /etc/traefik/acme/acme.json:/letsencrypt/acme.json
    labels:
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

  village-valet:
    build: https://github.com/ItsAMeNick/village-valet.git
    container_name: village-valet
    restart: always
    mem_limit: 500m
    env_file: village-valet/.env
    labels:
      - traefik.http.routers.village-valet.rule=Host(`village-valet.tk`,`www.village-valet.tk`)
      - traefik.http.routers.village-valet.tls=true
      - traefik.http.routers.village-valet.tls.certresolver=tls
    volumes:
      - /drone/village-valet/serviceAccountKey.json:/app/keys/serviceAccountKey.json

  village-valet_dev:
    build: https://github.com/ItsAMeNick/village-valet.git#dev
    container_name: village-valet
    restart: always
    mem_limit: 500m
    env_file: village-valet/.env
    labels:
      - traefik.http.routers.village-valet_dev.rule=Host(`beta.village-valet.tk`)
      - traefik.http.routers.village-valet_dev.tls=true
      - traefik.http.routers.village-valet_dev.tls.certresolver=tls
    volumes:
      - /drone/village-valet/serviceAccountKey.json:/app/keys/serviceAccountKey.json

