version: '2'
services:
    village-valet:
        build: https://github.com/ItsAMeNick/village-valet.git
        container_name: village-valet
        restart: always
        mem_limit: 500m
        ports:
         - "80:80"
         - "443:443"
        env_file: village-valet/.env
